{% set name = "databind.json" %}
{% set version = "1.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/databind.json-{{ version }}.tar.gz
  sha256: 4f2c47783ed52cbe5e483068c7b10b881e123201253d7cabd38a95fdec170a86

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<4.0
  run:
    - databind.core >=1.1.2,<2.0.0
    - nr.parsing.date >=1.0.1,<2.0.0
    - nr.preconditions >=0.0.4,<1.0.0
    - python >=3.7,<4.0
    - typing-extensions <4.0.0,>=3.10.0

test:
  imports:
    - databind
    - databind.json
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NiklasRosenstein/python-databind
  summary: De-/serialize Python dataclasses to or from JSON payloads. Compatible with Python 3.7 and newer.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - NiklasRosenstein
