{% set name = "databind.json" %}
{% set version = "1.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/databind.json-{{ version }}.tar.gz
  sha256: cd91f7fe91ef211a69cc1fe0bedaa4f65dccac7ec8f2b2ae91d31bf142a118f7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<4.0
  run:
    - databind.core >=1.2.2,<2.0.0
    - nr.optional >=0.1.1,<1.0.0
    - nr.parsing.date >=1.0.1,<2.0.0
    - nr.preconditions >=0.0.4,<1.0.0
    - python >=3.7,<4.0
    - typing-extensions <4.0.0,>=3.10.0

test:
  imports:
    - databind
    - databind.json
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NiklasRosenstein/python-databind
  summary: De-/serialize Python dataclasses to or from JSON payloads. Compatible with Python 3.7 and newer.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - NiklasRosenstein
